---
# Pre-commit hooks for code quality validation
# Install: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: check-case-conflict
      - id: detect-private-key

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: ['--config', '.markdownlint.json']

  # JavaScript/TypeScript formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, yaml, markdown]

  # Custom validation scripts
  - repo: local
    hooks:
      - id: validate-structure
        name: Validate project structure
        entry: scripts/pre-commit-validate-structure.sh
        language: system
        pass_filenames: false
        always_run: true

      - id: check-agents-md
        name: Check AGENTS.md exists and is valid
        entry: scripts/pre-commit-check-agents.sh
        language: system
        files: ^AGENTS\.md$
        pass_filenames: false
